name: ShadowVillageCore
main: com.github.fitexmage.ShadowVillageCore
version: 1.0.1
description: This is the Shadow Village Core.
depend: [Citizens]
author: Fitexmage

commands:
  svc:
    description: Shadow village core system.
    usage: ???
  svs:
    description: Shadow village support system.
    usage: ???
  sve:
    description: Shadow village ecology system.
    usage: ???
  svb:
    description: Shadow village black market.
    usage: ???

permissions:
  svc.version:
    description: Get current version of server. 
    default: true
  svc.help:
    description: Get a helper book.
    default: true
  svc.empower:
    description: Empower to control the core. 
    default: op
  svc.address:
    description: Get IP address of target player. 
    default: op
  svc.debug:
    description: Turn on or off debug mod.
    default: op
  sve.summon.shadowman:
    description: Summon shadow man.
    default: op
  sve.summon.shadowbeast:
    description: Summon shadow beast.
    default: op
  sve.summon.shadowsoul:
    description: Summon shadow soul.
    default: op
  svb.give.shadowstone:
    description: Give self shadow stones.
    default: op
  svb.give.shadowsoulbook:
    description: Give self a shadow soul book.
    default: op
  svb.give.serverequipment:
    description: Give self all server equipment.
    default: op
  svb.lookup.shadowstone:
    description: Look up amount of shadow stones in inventory.
    default: true
  svb.lookup.possibilities:
      description: Look up possibilities of gamble items.
      default: true
  svb.gamble.sword:
    description: Gamble on sword.
    default: true
  svb.gamble.bow:
    description: Gamble on bow.
    default: true
  svb.gamble.helmet:
    description: Gamble on helmet.
    default: true
  svb.gamble.chestplate:
    description: Gamble on chestplate.
    default: true
  svb.gamble.leggings:
    description: Gamble on leggings.
    default: true
  svb.gamble.boots:
    description: Gamble on boots.
    default: true
  svb.set.damage:
    description: Set the damage of item in hand.
    default: op
  svb.set.health:
    description: Set the health buff of item in hand.
    default: op
  svb.set.name:
    description: Set the name of item in hand.
    default: op
